name: Coverage
on:
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Collect coverage
        run: |
          pub get
          pub global activate coverage
          pub global run coverage:test_with_coverage
      - uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
